package e0056_Exception_1;

public class Exc2 {
    public static void main(String[] args) {
        System.out.println("1");
//
//        try {
//            System.out.println(args[3]);
//            throw new Error();
//        } catch (Exception e) {
//            e.printStackTrace();
//            try {
//                throw new RuntimeException();
//            } catch (RuntimeException exception) {
//
//            }
//
//
//        } catch (RuntimeException e) {
//            e.printStackTrace();
//        } finally {
//            System.out.println("4");
//        }
//
//        System.out.println("5");
//    }
//

    }
}
